### ISSUE TITLE
What are similarities and differences between tron and moya? 

### ISSUE THREAD

**Issue by rlam3** [MLSDev/TRON#19] opened 2016-10-19 23:44 UTC
What are similarities and differences between tron and moya? 

Any trade offs? 
Does tron support rxswift? 
How does tron handle with JWT based authentication and requests?

New to tron. Thanks!

**Comment by DenTelezhkin** [comment] 2016-10-20 07:12
Hey!
First of all, Moya was one of the inspirations for us, when we built TRON initially. So, there are some similarities between those frameworks, but there are a lot of ways, where we decided to go different directions.

First and probably most important of all, Moya hides underlying implementation details and does not expose a fact that it's built on top of Alamofire. We did this in TRON 0.x releases, but then decided against it. Exposing Alamofire internal structure leads to more complex implementation for new developers, however for developers familiar with Alamofire and TRON, it allows to use much more features then Moya does. For example, since all TRON requests return Alamofire.Request, you could simply `debugPrint(request)` to receive cURL of the request. This is functionality of the Alamofire, that is not exposed by Moya for example(at least i'm not aware of it). Also, we don't duplicate functionality of Alamofire, if it's not needed - up until recently(https://github.com/Moya/Moya/commit/7b48a8e84de4e1499c3faf38f18539ced54e7ed2) Moya had complete duplicate of HTTP Method enum of Alamofire.

Second, Moya does not have built-in response serialization. It follows Alamofire convention of several response serializers, that could be added on top of request. TRON requires you to expicitly set resulting model using generic constraints for each request. 

Third, Moya has concept of "target", described here: https://github.com/Moya/Moya/blob/master/docs/Targets.md. TRON does not have it, instead you directly create  each request like so: https://github.com/MLSDev/TRON#crud.

As you can see, difference is really big. Unfortunately, we did not use Moya in our projects, so it's really hard to speak about trade-offs. Most of what i'm talking about partly looks like TRON advertisements, so sorry about that. It would be great to know Moya guys thoughts about TRON as well.

As for similarities, plugin system in 1.x release was almost identical to Moya plugin system(although it's getting a major overhaul for `TRON 2.x`). We also support stubbing of network requests out of the box, and also provide reactive extension for RxSwift.

We don't have support for ReactiveCocoa(although you could easily add it on top of current implementation, since RxSwift extension is really really small and straightforward - https://github.com/MLSDev/TRON/blob/master/Source/RxSwift/Tron%2BRxSwift.swift).

And as for JWT, we did not use it in our projects, so i'm not sure we are supporting it. Can you describe how you use JWT authentication with Moya? Maybe we can come up with a way to use it with TRON.

Hopefully this answers your question.

**Closed as completed by DenTelezhkin** 2016-10-20 07:12 UTC
